### ISSUE TITLE
Avoid double equals "=="

### ISSUE THREAD

**Issue by polyccon** [fac-12/teamQ#50]
I'm unsure whether you used it intentionally but it's general good practice to use "===" everywhere as the double gives flexibility with data types and could cause unintentional bugs.

**Comment by shannonjensen** [comment]
@polyccon, actually changing == to === introduced a bug in our findObj function where we are trying to identify an object by one of its key value pairs. I would think that for strings/numbers/etc then you should default to == and for arrays and objects you should default to ===, not apply === .
